// Copyright (c) 2013 NetEase Youdao Inc. and other heX contributors.
// All rights reserved. Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#ifndef HEX_INCLUDE_HEX_PACK_RESOURCES_H_
#define HEX_INCLUDE_HEX_PACK_RESOURCES_H_

/*#define IDR_HEX_DEVTOOLS 60600
#define IDR_HEX_CREDITS_HTML 60601
#define IDR_HEX_CREDITS_JS 60602
#define IDR_HEX_CREDITS_SWIFTSHADER_JPG 60603
#define IDR_HEX_LICENSE_TXT 60604
#define IDR_HEX_VERSION_HTML 60605
#define IDR_HEX_VERSION_LOGO 60606
#define IDR_HEX_CLOSE 60610
#define IDR_HEX_CLOSE_HOVER 60611
#define IDR_HEX_CLOSE_PRESSED 60612
#define IDR_HEX_MINIMIZE 60613
#define IDR_HEX_MINIMIZE_HOVER 60614
#define IDR_HEX_MINIMIZE_PRESSED 60615
#define IDR_HEX_MAXIMIZE 60616
#define IDR_HEX_MAXIMIZE_HOVER 60617
#define IDR_HEX_MAXIMIZE_PRESSED 60618
#define IDR_HEX_RESTORE 60619
#define IDR_HEX_RESTORE_HOVER 60620
#define IDR_HEX_RESTORE_PRESSED 60621*/



#endif  // HEX_INCLUDE_HEX_PACK_RESOURCES_H_
